### ISSUE TITLE
Parameter padding problems in the ndr class

### ISSUE THREAD

**Issue by timothee-sm** [hakril/PythonForWindows#18]
The padding of a parameter depends on its size and should not always be aligned on 4 bytes.
cf [Alignment of Primitive Types - DCE 1.1](https://pubs.opengroup.org/onlinepubs/009629399/toc.pdf#page=660)

An example of a RPC server to test this bug : [RPC_Test.zip](https://github.com/hakril/PythonForWindows/files/4752648/RPC_Test.zip)

The request is accepted but the RPC server does not receive the correct parameter values.

**Comment by hakril** [comment]
Hi,

Thank you for the report and the information.
I have push a first fix that should better match the expected behaviour of NDR padding for both parameters and structures. (d8ac02e6a2b)
I have also added a test file for NDR related code (https://github.com/hakril/PythonForWindows/blob/dev/tests/test_ndr.py) that should help prove bugs and test for non-regression.
In its current state, I am not sur about the padding for ``conformant structures`` and structures containing pointer. I will try to test these behaviour soon.
