### ISSUE TITLE
Is there something wrong in thread.teb_base？

### ISSUE THREAD

**Issue by prprDog** [hakril/PythonForWindows#41]
My Windows is 64bit, and when runing 64bit process , thread.teb_base is okay.
But when I run 32bit process, thread.teb_base is wrong, because it is not same as x32dbg result:
My code resuit
![teb](https://user-images.githubusercontent.com/22913512/182751233-a378560c-28de-4108-898e-5c0c744e6419.png)

x32dbg views:
![x32dbg](https://user-images.githubusercontent.com/22913512/182751274-39a56613-b2d8-437f-9af4-f3c9b579dfc8.png)

My python code:
```
    targetProcess = None
    processList = windows.system.enumerate_processes()
    for process in processList:
        print("process name:", process.name)
        # HWorks32.exe
        if process.name == "HWorks32.exe":
            targetProcess = process

    threadList = targetProcess.threads

    for thread in threadList:
        teb = thread.teb_base
        print("teb:", hex(teb))
```
I sure the x32dbg result is true, because I actually wanna get stackBaseAddress from teb:
```
stackBaseAddress = process.read_ptr(teb + 4)
```
The above code would get some 0x0 stackBaseAddress and would throw exception if I read it, but In x32dbg, I search it manually, the result is okay.

And you can find that the difference x32dbg teb between code result is 0x2000! It mean that I can add 0x2000 to very teb in my code and can get the true teb!

**Comment by hakril** [comment]
Hi,

Thank you for the feedback and the question.
This difference is due to the `WoW64` technology (https://docs.microsoft.com/en-us/windows/win32/winprog64/wow64-implementation-details) and what `x32dbg` and `PythonForWindows` consider being the TEB.

In Wow64 process (32bits process on 64bits computer) each process have 2 PEB and each thread 2 TEB.
Indeed for each of these structure, it exists a 64bits version and a 32bits version of these in memory.

As `x32dbg`  is a 32bits debugger/process it will only see the 32bits TEB whereas what PythonForWindows returns is the 64bits TEB for a thread. I do not offer a way to retreive the TEB32 for now.

I could do some changes to allow retrieving the TEB32 & TEB64, just as I do for the PEB32/PEB64. Something like `process.teb_base_syswow`

Here is some mix of PythonForWindows / WinDBG output to show this :

===== TEB : PythonForWindows ====
```python
>>> p
<WinProcess "winver.exe" pid 9080 at 0x65bad08L>
>>> p.bitness
32
>>> hex(p.threads[4].teb_base)
'0xa14000L'
````
===== TEB : WinDBG====

```
0:004> !teb
Wow64 TEB32 at 0000000000a16000
    ExceptionList:        00000000ffffffff
    StackBase:            0000000006060000
    StackLimit:           000000000605c000
...
    Self:                 0000000000a16000
    EnvironmentPointer:   0000000000000000
    ClientId:             0000000000002378 . 00000000000010a8
    RpcHandle:            0000000000000000
    Tls Storage:          0000000000000000
    PEB Address:          0000000000a03000


Wow64 TEB at 0000000000a14000
    ExceptionList:        0000000000a16000
    StackBase:            000000000601fd20
    StackLimit:           0000000006018000
...
    Self:                 0000000000a14000
    EnvironmentPointer:   0000000000000000
    ClientId:             0000000000002378 . 00000000000010a8
    RpcHandle:            0000000000000000
    Tls Storage:          0000000000000000
    PEB Address:          0000000000a02000
...
```


===== PEB: PythonForWindows ====

```python
>>> hex(p.peb_addr)
'0xa03000L'
>>> hex(p.peb_syswow_addr)
'0xa02000L'
```

===== PEB: WinDBG ====

```
0:004> !peb
Wow64 PEB32 at a03000
    InheritedAddressSpace:    No
    ReadImageFileExecOptions: No
    BeingDebugged:            Yes
    ImageBaseAddress:         0000000000cf0000
    NtGlobalFlag:             0
    NtGlobalFlag2:            0
    Ldr                       00000000776b89c0
...


Wow64 PEB at 0000000000a02000
    InheritedAddressSpace:    No
    ReadImageFileExecOptions: No
    BeingDebugged:            Yes
    ImageBaseAddress:         0000000000cf0000
    NtGlobalFlag:             0
    NtGlobalFlag2:            0
    Ldr                       00007fff42b7a120

```

**Comment by prprDog** [comment]
> Hi,
> 
> Thank you for the feedback and the question. This difference is due to the `WoW64` technology (https://docs.microsoft.com/en-us/windows/win32/winprog64/wow64-implementation-details) and what `x32dbg` and `PythonForWindows` consider being the TEB.
> 
> In Wow64 process (32bits process on 64bits computer) each process have 2 PEB and each thread 2 TEB. Indeed for each of these structure, it exists a 64bits version and a 32bits version of these in memory.
> 
> As `x32dbg` is a 32bits debugger/process it will only see the 32bits TEB whereas what PythonForWindows returns is the 64bits TEB for a thread. I do not offer a way to retreive the TEB32 for now.
> 
> I could do some changes to allow retrieving the TEB32 & TEB64, just as I do for the PEB32/PEB64. Something like `process.teb_base_syswow`
> 
> Here is some mix of PythonForWindows / WinDBG output to show this :
> 
> ===== TEB : PythonForWindows ====
> 
> ```python
> >>> p
> <WinProcess "winver.exe" pid 9080 at 0x65bad08L>
> >>> p.bitness
> 32
> >>> hex(p.threads[4].teb_base)
> '0xa14000L'
> ```
> 
> ===== TEB : WinDBG====
> 
> ```
> 0:004> !teb
> Wow64 TEB32 at 0000000000a16000
>     ExceptionList:        00000000ffffffff
>     StackBase:            0000000006060000
>     StackLimit:           000000000605c000
> ...
>     Self:                 0000000000a16000
>     EnvironmentPointer:   0000000000000000
>     ClientId:             0000000000002378 . 00000000000010a8
>     RpcHandle:            0000000000000000
>     Tls Storage:          0000000000000000
>     PEB Address:          0000000000a03000
> 
> 
> Wow64 TEB at 0000000000a14000
>     ExceptionList:        0000000000a16000
>     StackBase:            000000000601fd20
>     StackLimit:           0000000006018000
> ...
>     Self:                 0000000000a14000
>     EnvironmentPointer:   0000000000000000
>     ClientId:             0000000000002378 . 00000000000010a8
>     RpcHandle:            0000000000000000
>     Tls Storage:          0000000000000000
>     PEB Address:          0000000000a02000
> ...
> ```
> 
> ===== PEB: PythonForWindows ====
> 
> ```python
> >>> hex(p.peb_addr)
> '0xa03000L'
> >>> hex(p.peb_syswow_addr)
> '0xa02000L'
> ```
> 
> ===== PEB: WinDBG ====
> 
> ```
> 0:004> !peb
> Wow64 PEB32 at a03000
>     InheritedAddressSpace:    No
>     ReadImageFileExecOptions: No
>     BeingDebugged:            Yes
>     ImageBaseAddress:         0000000000cf0000
>     NtGlobalFlag:             0
>     NtGlobalFlag2:            0
>     Ldr                       00000000776b89c0
> ...
> 
> 
> Wow64 PEB at 0000000000a02000
>     InheritedAddressSpace:    No
>     ReadImageFileExecOptions: No
>     BeingDebugged:            Yes
>     ImageBaseAddress:         0000000000cf0000
>     NtGlobalFlag:             0
>     NtGlobalFlag2:            0
>     Ldr                       00007fff42b7a120
> ```

Thanks for reply! Can I add 0x2000 to 64bits TEB then get 32bits one? It seems strange, because I don't know why they just difference of 0x2000 between them.

**Comment by hakril** [comment]
After your issue, I changed the behavior of `Thread.teb_base` to match the behavior of `Process.peb_addr`.

This means that on a Wow64 Process, `Thread.teb_base` will return the TEB32 address (the one you seek) and  `Thread.teb_syswow_base` will returns the TEB64 for such process.
This match the `Process.peb / Process.peb_syswow` behavior and naming.

https://github.com/hakril/PythonForWindows/blob/master/windows/winobject/process.py#L893
https://github.com/hakril/PythonForWindows/blob/master/windows/winobject/process.py#L908

Your code should work with `teb_base` if you pull from master.

For information, the 0x2000 difference is because Windows allocate both TEB32 & TEB64 on the same allocation and place the TEB32 at `Teb32Base = (PTEB32)((PCHAR)TebBase + ROUND_TO_PAGES (sizeof(TEB)));`

**Comment by prprDog** [comment]
> 

Thanks a lot!
